//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviews.EFRepository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantReview
    {
        public int SystemId { get; set; }
        public int RestaurantSystemId { get; set; }
        public int ReviewerSystemId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public byte NumberOfStars { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
