version: '3'

volumes:
    mssql-volume:

services:
    mssql:
        container_name: mssql
        image: microsoft/mssql-server-linux
        ports:
            - "1433:1433"
        volumes:
            - mssql-volume:/var/opt/mssql
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: D3vTe&ting