//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviews.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid RestaurantId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User CreatedBy { get; set; }
    }
}
