//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; private set; }
        public int RestaurantId { get; set; }
        public int Score { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public string User { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
