CREATE TABLE [dbo].[Review]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[RestaurantId] UNIQUEIDENTIFIER NOT NULL,
	[Rating] INT NOT NULL,
	[ReviewText] NVARCHAR(500),
	CONSTRAINT FK_Review_User FOREIGN KEY (UserId) REFERENCES [dbo].[User],
	CONSTRAINT FK_Review_Restaurant FOREIGN KEY (RestaurantId) REFERENCES [dbo].[Restaurant]
)
